# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.7
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties
mod_id=turtlerpgclasses
mod_name=TurtleBoi's RPG Classes
mod_license=MIT License
mod_version=0.3.3
mod_group_id=net.turtleboi.turtlerpgclasses
mod_authors=TurtleBoi
mod_description=TurtleBoi's RPG Classes introduce 3 classic RPG classes to Minecraft, each with unique talent trees, subclasses, and skills! \nPlay as a Warrior, Ranger, or Mage, each with distinctive attributes and capabilities.
